name: Bonjour
on: [push]
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
    - run: cat README.md | cowsay -f vader