name: Cantina
on: [push, pull_request]
jobs:
  cantina-menu:
    runs-on: ubuntu-18.04 # Required for linkchecker
    steps:
    - uses: actions/checkout@v2 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
    - run: sudo apt-get update && sudo apt-get install -y asciidoctor linkchecker # Installation des outils requis
    # Génération du dossier livrable `./dist/` avec test inclus
    - run: make clean
    - run: make test
    - run: make dist
    - uses: netlify/actions/cli@master # Déploiement sur Netlify
      if: contains(github.ref, 'main')
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} # A définir dans https://github.com/<votre dépôt github>/settings/secrets/actions
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # A définir dans https://github.com/<votre dépôt github>/settings/secrets/actions
